import { type BaseBarcodeTemplateRepository } from "./BaseBarcodeTemplateRepository.js";
import { type BaseClassificationRepository } from "./BaseClassificationRepository.js";
import { type BaseCustomerDisplayRepository } from "./BaseCustomerDisplayRepository.js";
import { type BaseCustomerGroupRepository } from "./BaseCustomerGroupRepository.js";
import { type BaseCustomerRepository } from "./BaseCustomerRepository.js";
import { type BaseEnterpriseRepository } from "./BaseEnterpriseRepository.js";
import { type BaseGiftCardRepository } from "./BaseGiftCardRepository.js";
import { type BaseLoyaltyRepository } from "./BaseLoyaltyRepository.js";
import { type BaseMovementRepository } from "./BaseMovementRepository.js";
import { type BaseOutletRepository } from "./BaseOutletRepository.js";
import { type BasePaymentMethodRepository } from "./BasePaymentMethodRepository.js";
import { type BasePriceListRepository } from "./BasePriceListRepository.js";
import { type BasePriceSetRepository } from "./BasePriceSetRepository.js";
import { type BaseProductRepository } from "./BaseProductRepository.js";
import { type BasePromotionCategoryRepository } from "./BasePromotionCategoryRepository.js";
import { type BasePromotionRepository } from "./BasePromotionRepository.js";
import { type BaseReceiptRepository } from "./BaseReceiptRepository.js";
import { type BaseRegisterRepository } from "./BaseRegisterRepository.js";
import { type BaseSalesKeyRepository } from "./BaseSalesKeyRepository.js";
import { type BaseSalesRepository } from "./BaseSalesRepository.js";
import { type BaseStocktakeAccumulatedRepository } from "./BaseStocktakeAccumulatedRepository.js";
import { type BaseStocktakeRepository } from "./BaseStocktakeRepository.js";
import { type BaseStocktakeScannedRepository } from "./BaseStocktakeScannedRepository.js";
import { type BaseSupplierRepository } from "./BaseSupplierRepository.js";
import { type BaseTakingsRepository } from "./BaseTakingsRepository.js";
import { type BaseTaxRateRepository } from "./BaseTaxRateRepository.js";
import { type BaseTransfereeRepository } from "./BaseTransfereeRepository.js";
import { type BaseVendorConnectionRepository } from "./BaseVendorConnectionRepository.js";

export interface DataSourceTables {
    products: BaseProductRepository;
    customers: BaseCustomerRepository;
    customerGroups: BaseCustomerGroupRepository;
    promotions: BasePromotionRepository;
    promotionCategories: BasePromotionCategoryRepository;
    priceLists: BasePriceListRepository;
    paymentMethods: BasePaymentMethodRepository;
    salesKeys: BaseSalesKeyRepository;
    receipts: BaseReceiptRepository;
    giftCards: BaseGiftCardRepository;
    loyalty: BaseLoyaltyRepository;
    customerDisplays: BaseCustomerDisplayRepository;
    sales: BaseSalesRepository;
    brands: BaseClassificationRepository;
    categories: BaseClassificationRepository;
    families: BaseClassificationRepository;
    tags: BaseClassificationRepository;
    outlets: BaseOutletRepository;
    registers: BaseRegisterRepository;
    taxRates: BaseTaxRateRepository;
    takings: BaseTakingsRepository;
    suppliers: BaseSupplierRepository;
    priceSets: BasePriceSetRepository;
    transferees: BaseTransfereeRepository;
    movements: BaseMovementRepository;
    stocktakes: BaseStocktakeRepository;
    stocktakeScanned: BaseStocktakeScannedRepository;
    stocktakeAccumulated: BaseStocktakeAccumulatedRepository;
    barcodeTemplates: BaseBarcodeTemplateRepository;
    vendorConnections: BaseVendorConnectionRepository;
    enterprises: BaseEnterpriseRepository;
}
