import { BaseBarcodeTemplateRepository } from "./BaseBarcodeTemplateRepository.js";
import { BaseClassificationRepository } from "./BaseClassificationRepository.js";
import { BaseCustomerDisplayRepository } from "./BaseCustomerDisplayRepository.js";
import { BaseCustomerGroupRepository } from "./BaseCustomerGroupRepository.js";
import { BaseCustomerRepository } from "./BaseCustomerRepository.js";
import { BaseEnterpriseRepository } from "./BaseEnterpriseRepository.js";
import { BaseGiftCardRepository } from "./BaseGiftCardRepository.js";
import { BaseLoyaltyRepository } from "./BaseLoyaltyRepository.js";
import { BaseMovementRepository } from "./BaseMovementRepository.js";
import { BaseOutletRepository } from "./BaseOutletRepository.js";
import { BasePaymentMethodRepository } from "./BasePaymentMethodRepository.js";
import { BasePriceListRepository } from "./BasePriceListRepository.js";
import { BasePriceSetRepository } from "./BasePriceSetRepository.js";
import { BaseProductRepository } from "./BaseProductRepository.js";
import { BasePromotionCategoryRepository } from "./BasePromotionCategoryRepository.js";
import { BasePromotionRepository } from "./BasePromotionRepository.js";
import { BaseReceiptRepository } from "./BaseReceiptRepository.js";
import { BaseRegisterRepository } from "./BaseRegisterRepository.js";
import { BaseSalesKeyRepository } from "./BaseSalesKeyRepository.js";
import { BaseSalesRepository } from "./BaseSalesRepository.js";
import { BaseStocktakeAccumulatedRepository } from "./BaseStocktakeAccumulatedRepository.js";
import { BaseStocktakeRepository } from "./BaseStocktakeRepository.js";
import { BaseStocktakeScannedRepository } from "./BaseStocktakeScannedRepository.js";
import { BaseSupplierRepository } from "./BaseSupplierRepository.js";
import { BaseTakingsRepository } from "./BaseTakingsRepository.js";
import { BaseTaxRateRepository } from "./BaseTaxRateRepository.js";
import { BaseTransfereeRepository } from "./BaseTransfereeRepository.js";
import { BaseVendorConnectionRepository } from "./BaseVendorConnectionRepository.js";

export interface DataSourceTables {
    products: BaseProductRepository;
    customers: BaseCustomerRepository;
    customerGroups: BaseCustomerGroupRepository;
    promotions: BasePromotionRepository;
    promotionCategories: BasePromotionCategoryRepository;
    priceLists: BasePriceListRepository;
    paymentMethods: BasePaymentMethodRepository;
    salesKeys: BaseSalesKeyRepository;
    receipts: BaseReceiptRepository;
    giftCards: BaseGiftCardRepository;
    loyalty: BaseLoyaltyRepository;
    customerDisplays: BaseCustomerDisplayRepository;
    sales: BaseSalesRepository;
    brands: BaseClassificationRepository;
    categories: BaseClassificationRepository;
    families: BaseClassificationRepository;
    tags: BaseClassificationRepository;
    outlets: BaseOutletRepository;
    registers: BaseRegisterRepository;
    taxRates: BaseTaxRateRepository;
    takings: BaseTakingsRepository;
    suppliers: BaseSupplierRepository;
    priceSets: BasePriceSetRepository;
    transferees: BaseTransfereeRepository;
    movements: BaseMovementRepository;
    stocktakes: BaseStocktakeRepository;
    stocktakeScanned: BaseStocktakeScannedRepository;
    stocktakeAccumulated: BaseStocktakeAccumulatedRepository;
    barcodeTemplates: BaseBarcodeTemplateRepository;
    vendorConnections: BaseVendorConnectionRepository;
    enterprises: BaseEnterpriseRepository;
}
